Updated cluster-role.yaml to run Kubeflow Faring from Kubeflow Pipeline
When someone runs Kubeflow Faring from Kubeflow Pipeline, he/she will get below error:
IOError: [Errno 2] No such file or directory: ‘/etc/secrets/user-gcp-sa.json’

Reason:
When Kubeflow Fairing tries to launch the pod for model training like LightGBM distributed parallel training, it tries to check the presence of the secret by using "list" instead of "get" and when list fails due to lack of permission, it just does not attach any secrets to the pod. This cause whole Kubeflow pipeline fail.

Solution:
Updated the pipeline-runner ClusterRole to allow the pipeline-runner to list the secrets. This help me run Kubeflow fairing from Kubeflow pipeline successfully.